//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WebSite.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string This_site_offers_a_place_to_download_the_NetRisk_app_ {
            get {
                return ResourceManager.GetString("This site offers a place to download the NetRisk app.", resourceCulture);
            }
        }
        
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        internal static string Download_the_NetRisk_app_for_your_system_ {
            get {
                return ResourceManager.GetString("Download the NetRisk app for your system.", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string NetRisk_is_an_open_source_risk_management_application_ {
            get {
                return ResourceManager.GetString("NetRisk is an open source risk management application.", resourceCulture);
            }
        }
        
        internal static string It_is_open_source_and_can_be_used_free_of_charges_ {
            get {
                return ResourceManager.GetString("It is open source and can be used free of charges.", resourceCulture);
            }
        }
        
        internal static string This_is_a_private_server_ {
            get {
                return ResourceManager.GetString("This is a private server.", resourceCulture);
            }
        }
        
        internal static string Vulnerability_Details {
            get {
                return ResourceManager.GetString("Vulnerability Details", resourceCulture);
            }
        }
        
        internal static string Vulnerability_Fix_Report {
            get {
                return ResourceManager.GetString("Vulnerability Fix Report", resourceCulture);
            }
        }
        
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        internal static string Respondent {
            get {
                return ResourceManager.GetString("Respondent", resourceCulture);
            }
        }
        
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        internal static string Fixer_Name {
            get {
                return ResourceManager.GetString("Fixer Name", resourceCulture);
            }
        }
        
        internal static string Fixer_Email {
            get {
                return ResourceManager.GetString("Fixer Email", resourceCulture);
            }
        }
        
        internal static string Proposed_Fix_Date {
            get {
                return ResourceManager.GetString("Proposed Fix Date", resourceCulture);
            }
        }
        
        internal static string Find_Request {
            get {
                return ResourceManager.GetString("Find Request", resourceCulture);
            }
        }
        
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        internal static string Fix {
            get {
                return ResourceManager.GetString("Fix", resourceCulture);
            }
        }
        
        internal static string Ask_for_more_details {
            get {
                return ResourceManager.GetString("Ask for more details", resourceCulture);
            }
        }
        
        internal static string Reject_Fix {
            get {
                return ResourceManager.GetString("Reject Fix", resourceCulture);
            }
        }
        
        internal static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
    }
}
