//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSite.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the NetRisk app for your system..
        /// </summary>
        internal static string Download_the_NetRisk_app_for_your_system_ {
            get {
                return ResourceManager.GetString("Download the NetRisk app for your system.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Request.
        /// </summary>
        internal static string Find_Request {
            get {
                return ResourceManager.GetString("Find Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixer Email.
        /// </summary>
        internal static string Fixer_Email {
            get {
                return ResourceManager.GetString("Fixer Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixer Name.
        /// </summary>
        internal static string Fixer_Name {
            get {
                return ResourceManager.GetString("Fixer Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is open source and can be used free of charges..
        /// </summary>
        internal static string It_is_open_source_and_can_be_used_free_of_charges_ {
            get {
                return ResourceManager.GetString("It is open source and can be used free of charges.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetRisk is an open source risk management application..
        /// </summary>
        internal static string NetRisk_is_an_open_source_risk_management_application_ {
            get {
                return ResourceManager.GetString("NetRisk is an open source risk management application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Fix Date.
        /// </summary>
        internal static string Proposed_Fix_Date {
            get {
                return ResourceManager.GetString("Proposed Fix Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respondent.
        /// </summary>
        internal static string Respondent {
            get {
                return ResourceManager.GetString("Respondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a private server..
        /// </summary>
        internal static string This_is_a_private_server_ {
            get {
                return ResourceManager.GetString("This is a private server.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site offers a place to download the NetRisk app..
        /// </summary>
        internal static string This_site_offers_a_place_to_download_the_NetRisk_app_ {
            get {
                return ResourceManager.GetString("This site offers a place to download the NetRisk app.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Details.
        /// </summary>
        internal static string Vulnerability_Details {
            get {
                return ResourceManager.GetString("Vulnerability Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability Fix Report.
        /// </summary>
        internal static string Vulnerability_Fix_Report {
            get {
                return ResourceManager.GetString("Vulnerability Fix Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
