using DAL.Context;
using DAL.Entities;
using DAL.Enums;
using Microsoft.EntityFrameworkCore;
using Tools.Risks;

namespace ServerServices.Governance;

/// <summary>
/// The pieces of the linkage chain's write path that both <see cref="RiskChainService"/> and the
/// legacy <c>RisksService</c> entity association share (Stage 9.1, S41 §5.4).
///
/// The legacy path mirrors <c>risk_to_entity</c> into <c>risk_chain_links</c> as <c>Legacy</c> rows,
/// in the same <c>SaveChanges</c> as the legacy write, for as long as the two coexist:
/// <list type="bullet">
/// <item>associate (r, e), e of a chain type → create (r, e) Legacy, unless (r, e) already exists with
/// any origin;</item>
/// <item>clean r → remove r's Legacy links whose entity left <c>risk_to_entity</c>, never a Declared one;</item>
/// <item>remove (r, e) → remove (r, e) only if it is Legacy.</item>
/// </list>
/// Every query here goes through the caller's scoped context; none uses IgnoreQueryFilters.
/// </summary>
public static class RiskChainPersistence
{
    /// <summary>The two unique indexes whose violation means "this link already exists".</summary>
    public static readonly string[] UniqueIndexes =
    [
        "uq_risk_chain_links_risk_id_entity_id",
        "uq_risk_chain_links_risk_id_host_id"
    ];

    /// <summary>
    /// True when <paramref name="exception"/> is MariaDB's duplicate-key error (1062) on one of the
    /// chain's unique indexes — recognised by the index name, which MariaDB puts in the message, so a
    /// duplicate on any other table is never mistaken for one here.
    /// </summary>
    public static bool IsDuplicateLink(DbUpdateException exception)
    {
        for (Exception? current = exception; current is not null; current = current.InnerException)
        {
            if (UniqueIndexes.Any(index => current.Message.Contains(index, StringComparison.Ordinal)))
                return true;
        }

        return false;
    }

    /// <summary>
    /// Stages the Legacy mirror of a new <c>risk_to_entity</c> row. Returns the staged link, or null
    /// when the entity is not of a chain type or (r, e) is already linked with either origin.
    /// </summary>
    public static RiskChainLink? MirrorAssociation(AuditableContext context, int riskId, Entity entity)
    {
        var level = RiskChainSchema.LevelOf(entity.DefinitionName);
        if (level is null) return null;

        var exists = context.RiskChainLinks.Any(l => l.RiskId == riskId && l.EntityId == entity.Id);
        if (exists) return null;

        var link = new RiskChainLink
        {
            RiskId = riskId,
            ChainLevel = level.Value,
            EntityId = entity.Id,
            Origin = RiskChainLinkOrigin.Legacy,
            CreatedAt = DateTime.UtcNow
        };

        context.RiskChainLinks.Add(link);
        return link;
    }

    /// <summary>
    /// Stages the removal of <paramref name="riskId"/>'s Legacy links whose entity is not in
    /// <paramref name="remainingEntityIds"/>. Declared links are never touched.
    /// </summary>
    public static void MirrorRemoval(AuditableContext context, int riskId, IReadOnlyCollection<int> remainingEntityIds)
    {
        var stale = context.RiskChainLinks
            .Where(l => l.RiskId == riskId && l.Origin == RiskChainLinkOrigin.Legacy && l.EntityId != null)
            .ToList()
            .Where(l => !remainingEntityIds.Contains(l.EntityId!.Value))
            .ToList();

        context.RiskChainLinks.RemoveRange(stale);
    }

    /// <summary>
    /// Saves a legacy write together with its staged mirror. If the mirror loses a race with a
    /// concurrent <c>POST</c> on the unique index, the link it wanted already exists — with whichever
    /// origin — and that satisfies the invariant, so the mirror is dropped and the save repeated: the
    /// legacy operation must not be undone because of its mirror (S41 §5.4).
    /// </summary>
    public static void SaveWithMirror(AuditableContext context, RiskChainLink? stagedMirror)
    {
        try
        {
            context.SaveChanges();
        }
        catch (DbUpdateException ex) when (stagedMirror is not null && IsDuplicateLink(ex))
        {
            context.Entry(stagedMirror).State = EntityState.Detached;
            DiscardStagedAuditRows(context);
            context.SaveChanges();
        }
    }

    /// <summary>
    /// The failed attempt left its audit rows — the JSON <c>audit</c> table and the field-level
    /// <c>audit_logs</c> — staged in the change tracker, including the "create" of the link that was
    /// never written. Both are regenerated by the next save, so the stale ones are dropped rather than
    /// written twice or written for something that did not happen.
    /// </summary>
    public static void DiscardStagedAuditRows(AuditableContext context)
    {
        foreach (var entry in context.ChangeTracker.Entries()
                     .Where(e => e.State == EntityState.Added && e.Entity is Audit or AuditLog)
                     .ToList())
        {
            entry.State = EntityState.Detached;
        }
    }
}
