---
version: 1.2
definitions:
  organization:
    isRoot: True
    properties: 
      name: 
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue:
      isMainOrganization: 
        type: Boolean
        label: Is Main Organization
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue: False
      numberOfEmployees:
        type: Integer
        label: Number Of Employees
        multiple: False
        maxSize: -1
        nullable: True
        defaultValue: 0 
  person:
    isRoot: True
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue:
      email:
        type: String
        label: Email
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue:
      phoneNumber:
        type: String
        label: Phone Number
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue:
  organizationUnit:
    isRoot: True
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue:
      mainOrganization:
        type: Definition(organization)
        label: Main Organization
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue:
      responsible:
        type: Definition(person)
        label: Responsible
        multiple: true
        maxSize: 250
        nullable: True
        defaultValue:
  businessProcess:
    isRoot: True
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue:
      organizationUnit:
        type: Definition(organizationUnit)
        label: Organization Unit
        multiple: True
        maxSize: -1
        nullable: False
        defaultValue: