---
version: 2.1
definitions:
  organization:
    isRoot: True
    iconKind: Company
    allowedChildren: 
      - organizationUnit
      - person
      - securityClassificationLevel
    properties: 
      name: 
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""  
      isMainOrganization: 
        type: Boolean
        label: Is Main Organization
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue: "False"
      numberOfEmployees:
        type: Integer
        label: Number Of Employees
        multiple: False
        maxSize: -1
        nullable: True
        defaultValue: "0" 
  person:
    isRoot: True
    iconKind: Account
    allowedChildren: 
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      email:
        type: String
        label: Email
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue: ""
      phoneNumber:
        type: String
        label: Phone Number
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue: ""
  team:
    isRoot: False
    iconKind: AccountGroup
    allowedChildren:
      - person
      - team
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      organizationUnit:
        type: Definition(organizationUnit)
        label: Organization Unit
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue: "Parent"
      leader:
        type: Definition(person)
        label: Leader
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue: ""
      members:
        type: Definition(person)
        label: Members
        multiple: True
        maxSize: 250
        nullable: True
        defaultValue: ""
      email:
        type: String
        label: Contact Email
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue: ""
      phoneNumber:
        type: String
        label: Phone Number
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue: ""
  organizationUnit:
    isRoot: False
    iconKind: OfficeBuilding
    allowedChildren: 
      - businessProcess
      - person
      - team
      - application
      - subOrganizationUnit
      - organizationDataGroup
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      mainOrganization:
        type: Definition(organization)
        label: Main Organization
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue: "Parent"
      responsible:
        type: Definition(person)
        label: Responsible
        multiple: true
        maxSize: 250
        nullable: True
        defaultValue: ""
  subOrganizationUnit:
    isRoot: False
    iconKind: OfficeBuildingCog
    allowedChildren:
      - subOrganizationUnit
      - businessProcess
      - person
      - application
      - team
      - organizationDataGroup
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      parentOrganizationUnit:
        type: Definition(organizationUnit)
        label: Parent Organization Unit
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue: "Parent"
      responsible:
        type: Definition(person)
        label: Responsible
        multiple: true
        maxSize: 250
        nullable: True
        defaultValue: ""
  securityClassificationLevel:
    isRoot: False
    iconKind: ClipboardListOutline
    allowedChildren:
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      description:
        type: String
        label: Description
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      mainOrganization:
        type: Definition(organization)
        label: Main Organization
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue: "Parent"
  organizationData:
    isRoot: False
    iconKind: FileDocumentOutline
    allowedChildren:
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      description:
        type: String
        label: Description
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      responsible:
        type: Definition(person)
        label: Responsible
        multiple: true
        maxSize: 250
        nullable: True
        defaultValue: ""
      securityClassification:
        type: Definition(securityClassificationLevel)
        label: securityClassificationLevel
        multiple: false
        maxSize: -1
        nullable: True
        defaultValue: ""
  organizationDataGroup:
    isRoot: False
    iconKind: FileCabinet
    allowedChildren:
      - organizationData
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      description:
        type: String
        label: Description
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      responsible:
        type: Definition(person)
        label: Responsible
        multiple: true
        maxSize: 250
        nullable: True
        defaultValue: ""
      mainOrganization:
        type: Definition(organization)
        label: Main Organization
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue: "Parent"
      securityClassification:
        type: Definition(securityClassificationLevel)
        label: securityClassificationLevel
        multiple: false
        maxSize: -1
        nullable: True
        defaultValue: ""
  application:
    isRoot: False
    iconKind: Application
    allowedChildren:
      - applicationModule
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      technology:
        type: String
        label: Technology
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue: ""
      responsible:
        type: Definition(person)
        label: Responsible
        multiple: true
        maxSize: 250
        nullable: True
        defaultValue: ""
      relatedBusinessProcess:
        type: Definition(businessProcess)
        label: RelatedBusinessProcess
        multiple: true
        maxSize: 250
        nullable: True
        defaultValue: ""
  applicationModule:
    isRoot: False
    iconKind: ApplicationBraces
    allowedChildren:
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      technology:
        type: String
        label: Technology
        multiple: False
        maxSize: 250
        nullable: True
        defaultValue: ""
      parentApplication:
        type: Definition(application)
        label: Application
        multiple: false
        maxSize: 250
        nullable: True
        defaultValue: "Parent"
  businessProcess:
    isRoot: True
    iconKind: HumanMaleBoardPoll
    allowedChildren:
    properties:
      name:
        type: String
        label: Name
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      description:
        type: String
        label: Description
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      objective:
        type: String
        label: Objective
        multiple: False
        maxSize: 250
        nullable: False
        defaultValue: ""
      isActive:
        type: Boolean
        label: Is Active
        multiple: False
        maxSize: -1
        nullable: False
        defaultValue: "True"
      organizationUnit:
        type: Definition(organizationUnit)
        label: Organization Unit
        multiple: True
        maxSize: -1
        nullable: False
        defaultValue: ""