using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using Xunit;

namespace WebSite.Tests.Views;

/// <summary>
/// Every stylesheet and script a view references resolves to a file under <c>wwwroot</c>. The
/// layout carried five tags pointing at <c>~/Content/themes/base</c> and <c>~/Scripts</c> — the
/// classic ASP.NET convention, which ASP.NET Core does not serve. They 404'd on every page load
/// and nothing said so: a missing static asset is not a build error. See CHANGELOG.md, [NEXT].
/// </summary>
public class StaticAssetReferenceTest
{
    /// <summary>
    /// Paths legitimately absent from <c>wwwroot</c> on disk, each with the reason. Nothing may
    /// be added here without one.
    /// </summary>
    private static readonly Dictionary<string, string> GeneratedAtBuild = new(StringComparer.Ordinal)
    {
        // The scoped-CSS bundle the Razor SDK emits from .cshtml.css files during build.
        ["/WebSite.styles.css"] = "generated by the Razor SDK, never checked in",
    };

    private static readonly Regex AssetReference = new(
        @"(?:href|src)\s*=\s*""(?<path>~?/[^""]+)""|@Url\.Content\(""(?<path2>~/[^""]+)""\)",
        RegexOptions.Compiled);

    [Fact]
    public void Every_referenced_static_asset_exists_in_wwwroot()
    {
        var webRoot = Path.Combine(ProjectRoot(), "wwwroot");
        var missing = new List<string>();

        foreach (var view in Directory.EnumerateFiles(ProjectRoot(), "*.cshtml", SearchOption.AllDirectories))
        {
            foreach (Match match in AssetReference.Matches(File.ReadAllText(view)))
            {
                var reference = match.Groups["path"].Success
                    ? match.Groups["path"].Value
                    : match.Groups["path2"].Value;

                var path = Normalise(reference);
                if (path is null || GeneratedAtBuild.ContainsKey(path)) continue;

                var onDisk = Path.Combine(webRoot, path.TrimStart('/').Replace('/', Path.DirectorySeparatorChar));
                if (!File.Exists(onDisk))
                {
                    missing.Add($"  {path}  ← {Path.GetFileName(view)}");
                }
            }
        }

        Assert.True(missing.Count == 0,
            "These views reference static assets that do not exist under wwwroot. Each one is a "
            + "404 on every page that renders the view:"
            + Environment.NewLine + string.Join(Environment.NewLine, missing.Distinct().Order()));
    }

    /// <summary>App-relative path, or null for anything not a local static file.</summary>
    private static string? Normalise(string reference)
    {
        // Protocol-relative CDN references are somebody else's to serve.
        if (reference.StartsWith("//", StringComparison.Ordinal)) return null;

        var path = reference.StartsWith('~') ? reference[1..] : reference;

        // asp-append-version and cache-busting query strings are not part of the file name.
        var query = path.IndexOfAny(['?', '#']);
        if (query >= 0) path = path[..query];

        // A Razor expression inside the path means the target is only known at render time.
        return path.Contains('@') ? null : path;
    }

    private static string ProjectRoot([CallerFilePath] string thisFile = "") =>
        Path.GetFullPath(Path.Combine(Path.GetDirectoryName(thisFile)!, "..", "..", "WebSite"));
}
