<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e5c54e6b-8f27-413f-8ad3-8ef3b57dba58</UserSecretsId>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>13</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" />
    <PackageReference Include="Microting.EntityFrameworkCore.MySql" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <Compile Remove="Entities\File.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Extensions\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Extensions\**" />
  </ItemGroup>
</Project>