
ALTER TABLE `assessment_runs`
    ADD COLUMN IF NOT EXISTS `HostId` int NULL AFTER `Comments`,
ADD CONSTRAINT `fkHost` FOREIGN KEY IF NOT EXISTS (`HostId`) REFERENCES `hosts` (`Id`) ON DELETE SET NULL;