//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIClient.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GUIClient.Resources.Localization_en_US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        internal static string Sys {
            get {
                return ResourceManager.GetString("Sys", resourceCulture);
            }
        }
        
        internal static string OperationalSystem {
            get {
                return ResourceManager.GetString("OperationalSystem", resourceCulture);
            }
        }
        
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string NoRegistrationMSG {
            get {
                return ResourceManager.GetString("NoRegistrationMSG", resourceCulture);
            }
        }
        
        internal static string RegistrationErrorMSG {
            get {
                return ResourceManager.GetString("RegistrationErrorMSG", resourceCulture);
            }
        }
        
        internal static string RegistrationNotAcceptedMSG {
            get {
                return ResourceManager.GetString("RegistrationNotAcceptedMSG", resourceCulture);
            }
        }
        
        internal static string NotAccepted {
            get {
                return ResourceManager.GetString("NotAccepted", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        internal static string NotImplementedMSG {
            get {
                return ResourceManager.GetString("NotImplementedMSG", resourceCulture);
            }
        }
        
        internal static string SelectAuthenticationMSG {
            get {
                return ResourceManager.GetString("SelectAuthenticationMSG", resourceCulture);
            }
        }
        
        internal static string ApplicationMN {
            get {
                return ResourceManager.GetString("ApplicationMN", resourceCulture);
            }
        }
        
        internal static string ExitMN {
            get {
                return ResourceManager.GetString("ExitMN", resourceCulture);
            }
        }
        
        internal static string WelcomeMSG {
            get {
                return ResourceManager.GetString("WelcomeMSG", resourceCulture);
            }
        }
        
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        internal static string LoggedAccount {
            get {
                return ResourceManager.GetString("LoggedAccount", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string ClientApproveErrorMSG {
            get {
                return ResourceManager.GetString("ClientApproveErrorMSG", resourceCulture);
            }
        }
        
        internal static string ClientRejectErrorMSG {
            get {
                return ResourceManager.GetString("ClientRejectErrorMSG", resourceCulture);
            }
        }
        
        internal static string ClientDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("ClientDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        internal static string RisksOverTime {
            get {
                return ResourceManager.GetString("RisksOverTime", resourceCulture);
            }
        }
        
        internal static string Assessments {
            get {
                return ResourceManager.GetString("Assessments", resourceCulture);
            }
        }
        
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        internal static string AssessmentNameInvalidMSG {
            get {
                return ResourceManager.GetString("AssessmentNameInvalidMSG", resourceCulture);
            }
        }
        
        internal static string AssessmentNameExistsMSG {
            get {
                return ResourceManager.GetString("AssessmentNameExistsMSG", resourceCulture);
            }
        }
        
        internal static string ErrorCreatingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingAssessmentMSG", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteAssessmentMSG {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssessmentMSG", resourceCulture);
            }
        }
        
        internal static string ErrorDeletingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingAssessmentMSG", resourceCulture);
            }
        }
        
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        internal static string Risk {
            get {
                return ResourceManager.GetString("Risk", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string AnswerAlreadyExistsMSG {
            get {
                return ResourceManager.GetString("AnswerAlreadyExistsMSG", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string ErrorSavingQuestionMSG {
            get {
                return ResourceManager.GetString("ErrorSavingQuestionMSG", resourceCulture);
            }
        }
        
        internal static string QuestionAlreadyExistsMSG {
            get {
                return ResourceManager.GetString("QuestionAlreadyExistsMSG", resourceCulture);
            }
        }
        
        internal static string ErrorSavingAnswersMSG {
            get {
                return ResourceManager.GetString("ErrorSavingAnswersMSG", resourceCulture);
            }
        }
        
        internal static string QuestionDoesNotExistsMSG {
            get {
                return ResourceManager.GetString("QuestionDoesNotExistsMSG", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteAssessmentQuestionMSG {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssessmentQuestionMSG", resourceCulture);
            }
        }
        
        internal static string ErrorDeletingAssessmentQuestionMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingAssessmentQuestionMSG", resourceCulture);
            }
        }
        
        internal static string ErrorOpeningExternalBrowserMSG {
            get {
                return ResourceManager.GetString("ErrorOpeningExternalBrowserMSG", resourceCulture);
            }
        }
        
        internal static string SAMLAuthenticationTimeoutMSG {
            get {
                return ResourceManager.GetString("SAMLAuthenticationTimeoutMSG", resourceCulture);
            }
        }
        
        internal static string LogoutQuit {
            get {
                return ResourceManager.GetString("LogoutQuit", resourceCulture);
            }
        }
        
        internal static string ControlStatistics {
            get {
                return ResourceManager.GetString("ControlStatistics", resourceCulture);
            }
        }
        
        internal static string Maturity {
            get {
                return ResourceManager.GetString("Maturity", resourceCulture);
            }
        }
        
        internal static string DesiredMaturity {
            get {
                return ResourceManager.GetString("DesiredMaturity", resourceCulture);
            }
        }
        
        internal static string ControlRisk {
            get {
                return ResourceManager.GetString("ControlRisk", resourceCulture);
            }
        }
        
        internal static string StrRiskPanel {
            get {
                return ResourceManager.GetString("StrRiskPanel", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string SubmissionDate {
            get {
                return ResourceManager.GetString("SubmissionDate", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        internal static string SubmittedBy {
            get {
                return ResourceManager.GetString("SubmittedBy", resourceCulture);
            }
        }
        
        internal static string RiskType {
            get {
                return ResourceManager.GetString("RiskType", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        internal static string RiskMustHaveASubjectMSG {
            get {
                return ResourceManager.GetString("RiskMustHaveASubjectMSG", resourceCulture);
            }
        }
        
        internal static string ErrorCreatingRiskMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingRiskMSG", resourceCulture);
            }
        }
        
        internal static string SaveOkMSG {
            get {
                return ResourceManager.GetString("SaveOkMSG", resourceCulture);
            }
        }
        
        internal static string SelectRiskMSG {
            get {
                return ResourceManager.GetString("SelectRiskMSG", resourceCulture);
            }
        }
        
        internal static string SelectRiskDeleteMSG {
            get {
                return ResourceManager.GetString("SelectRiskDeleteMSG", resourceCulture);
            }
        }
        
        internal static string RiskDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("RiskDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        internal static string StatusFilter {
            get {
                return ResourceManager.GetString("StatusFilter", resourceCulture);
            }
        }
        
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static string Scoring {
            get {
                return ResourceManager.GetString("Scoring", resourceCulture);
            }
        }
        
        internal static string Probability {
            get {
                return ResourceManager.GetString("Probability", resourceCulture);
            }
        }
        
        internal static string Impact {
            get {
                return ResourceManager.GetString("Impact", resourceCulture);
            }
        }
        
        internal static string PleaseSelectOneMSG {
            get {
                return ResourceManager.GetString("PleaseSelectOneMSG", resourceCulture);
            }
        }
        
        internal static string MitigationNotPlannedMSG {
            get {
                return ResourceManager.GetString("MitigationNotPlannedMSG", resourceCulture);
            }
        }
        
        internal static string PlanMitigation {
            get {
                return ResourceManager.GetString("PlanMitigation", resourceCulture);
            }
        }
        
        internal static string Mitigation {
            get {
                return ResourceManager.GetString("Mitigation", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        internal static string StrProjected {
            get {
                return ResourceManager.GetString("StrProjected", resourceCulture);
            }
        }
        
        internal static string Projected {
            get {
                return ResourceManager.GetString("Projected", resourceCulture);
            }
        }
        
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        internal static string Effort {
            get {
                return ResourceManager.GetString("Effort", resourceCulture);
            }
        }
        
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        internal static string PlannedDate {
            get {
                return ResourceManager.GetString("PlannedDate", resourceCulture);
            }
        }
        
        internal static string PlanningStrategy {
            get {
                return ResourceManager.GetString("PlanningStrategy", resourceCulture);
            }
        }
        
        internal static string SecurityRequirements {
            get {
                return ResourceManager.GetString("SecurityRequirements", resourceCulture);
            }
        }
        
        internal static string MitigationEffort {
            get {
                return ResourceManager.GetString("MitigationEffort", resourceCulture);
            }
        }
        
        internal static string MitigationCost {
            get {
                return ResourceManager.GetString("MitigationCost", resourceCulture);
            }
        }
        
        internal static string SecurityRecommendation {
            get {
                return ResourceManager.GetString("SecurityRecommendation", resourceCulture);
            }
        }
        
        internal static string StrMitigationOwner {
            get {
                return ResourceManager.GetString("StrMitigationOwner", resourceCulture);
            }
        }
        
        internal static string MitigationTeam {
            get {
                return ResourceManager.GetString("MitigationTeam", resourceCulture);
            }
        }
        
        internal static string MitigationOwner {
            get {
                return ResourceManager.GetString("MitigationOwner", resourceCulture);
            }
        }
        
        internal static string MitigationPercent {
            get {
                return ResourceManager.GetString("MitigationPercent", resourceCulture);
            }
        }
        
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        internal static string ErrorMitigationMSG {
            get {
                return ResourceManager.GetString("ErrorMitigationMSG", resourceCulture);
            }
        }
        
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        internal static string CloseRisk {
            get {
                return ResourceManager.GetString("CloseRisk", resourceCulture);
            }
        }
        
        internal static string RiskClosingErrorMSG {
            get {
                return ResourceManager.GetString("RiskClosingErrorMSG", resourceCulture);
            }
        }
        
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        internal static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        internal static string LastPasswordChange {
            get {
                return ResourceManager.GetString("LastPasswordChange", resourceCulture);
            }
        }
        
        internal static string PleaseEnterAValueMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValueMSG", resourceCulture);
            }
        }
        
        internal static string UsernameMustBeUniqueMSG {
            get {
                return ResourceManager.GetString("UsernameMustBeUniqueMSG", resourceCulture);
            }
        }
        
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        internal static string CleanAll {
            get {
                return ResourceManager.GetString("CleanAll", resourceCulture);
            }
        }
        
        internal static string EnterAValidEmailMSG {
            get {
                return ResourceManager.GetString("EnterAValidEmailMSG", resourceCulture);
            }
        }
        
        internal static string YouCannotDisableYourselfMSG {
            get {
                return ResourceManager.GetString("YouCannotDisableYourselfMSG", resourceCulture);
            }
        }
        
        internal static string RemovingYourAdminRightsMSG {
            get {
                return ResourceManager.GetString("RemovingYourAdminRightsMSG", resourceCulture);
            }
        }
        
        internal static string PleaseCorrectTheErrorsMSG {
            get {
                return ResourceManager.GetString("PleaseCorrectTheErrorsMSG", resourceCulture);
            }
        }
        
        internal static string FirstSelectAUserMSG {
            get {
                return ResourceManager.GetString("FirstSelectAUserMSG", resourceCulture);
            }
        }
        
        internal static string YouCannotDeleteYourselfMSG {
            get {
                return ResourceManager.GetString("YouCannotDeleteYourselfMSG", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteThisUserMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisUserMSG", resourceCulture);
            }
        }
        
        internal static string UnexpectedErrorMSG {
            get {
                return ResourceManager.GetString("UnexpectedErrorMSG", resourceCulture);
            }
        }
        
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        internal static string SaveDocumentMSG {
            get {
                return ResourceManager.GetString("SaveDocumentMSG", resourceCulture);
            }
        }
        
        internal static string AddDocumentMSG {
            get {
                return ResourceManager.GetString("AddDocumentMSG", resourceCulture);
            }
        }
        
        internal static string FileDeletionErrorMSG {
            get {
                return ResourceManager.GetString("FileDeletionErrorMSG", resourceCulture);
            }
        }
        
        internal static string FileDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("FileDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        internal static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        internal static string CreateEntity {
            get {
                return ResourceManager.GetString("CreateEntity", resourceCulture);
            }
        }
        
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        internal static string ErrorCreatingEntityMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingEntityMSG", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string EntitySavedSuccessMSG {
            get {
                return ResourceManager.GetString("EntitySavedSuccessMSG", resourceCulture);
            }
        }
        
        internal static string PleaseSelectAnItemMSG {
            get {
                return ResourceManager.GetString("PleaseSelectAnItemMSG", resourceCulture);
            }
        }
        
        internal static string AreYouSureYouWantToDeleteMSG {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteMSG", resourceCulture);
            }
        }
        
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        internal static string EditEntity {
            get {
                return ResourceManager.GetString("EditEntity", resourceCulture);
            }
        }
        
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        internal static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        internal static string organizationUnit {
            get {
                return ResourceManager.GetString("organizationUnit", resourceCulture);
            }
        }
        
        internal static string businessProcess {
            get {
                return ResourceManager.GetString("businessProcess", resourceCulture);
            }
        }
        
        internal static string Is_Main_Organization {
            get {
                return ResourceManager.GetString("Is Main Organization", resourceCulture);
            }
        }
        
        internal static string Number_Of_Employees {
            get {
                return ResourceManager.GetString("Number Of Employees", resourceCulture);
            }
        }
        
        internal static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        internal static string Main_Organization {
            get {
                return ResourceManager.GetString("Main Organization", resourceCulture);
            }
        }
        
        internal static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        internal static string Organization_Unit {
            get {
                return ResourceManager.GetString("Organization Unit", resourceCulture);
            }
        }
        
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        internal static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        internal static string Risks {
            get {
                return ResourceManager.GetString("Risks", resourceCulture);
            }
        }
        
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string MitigationPlanned {
            get {
                return ResourceManager.GetString("MitigationPlanned", resourceCulture);
            }
        }
        
        internal static string ManagerReviewed {
            get {
                return ResourceManager.GetString("ManagerReviewed", resourceCulture);
            }
        }
        
        internal static string ReviewNotDone {
            get {
                return ResourceManager.GetString("ReviewNotDone", resourceCulture);
            }
        }
        
        internal static string LastReview {
            get {
                return ResourceManager.GetString("LastReview", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string ReviewDecision {
            get {
                return ResourceManager.GetString("ReviewDecision", resourceCulture);
            }
        }
        
        internal static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        internal static string Risk_Review {
            get {
                return ResourceManager.GetString("Risk Review", resourceCulture);
            }
        }
        
        internal static string NextReview {
            get {
                return ResourceManager.GetString("NextReview", resourceCulture);
            }
        }
        
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        internal static string ErrorLoadingReviewMSG {
            get {
                return ResourceManager.GetString("ErrorLoadingReviewMSG", resourceCulture);
            }
        }
        
        internal static string NetRiskVersionMGS {
            get {
                return ResourceManager.GetString("NetRiskVersionMGS", resourceCulture);
            }
        }
        
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        internal static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        internal static string UpgradeNeededMSG {
            get {
                return ResourceManager.GetString("UpgradeNeededMSG", resourceCulture);
            }
        }
        
        internal static string Risk_review_by_time {
            get {
                return ResourceManager.GetString("Risk review by time", resourceCulture);
            }
        }
        
        internal static string Cost_vs_Risk {
            get {
                return ResourceManager.GetString("Cost vs Risk", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string Max_Risk {
            get {
                return ResourceManager.GetString("Max Risk", resourceCulture);
            }
        }
        
        internal static string Min_Risk {
            get {
                return ResourceManager.GetString("Min Risk", resourceCulture);
            }
        }
        
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        internal static string TeamMembers {
            get {
                return ResourceManager.GetString("TeamMembers", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteThisTeamMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisTeamMSG", resourceCulture);
            }
        }
        
        internal static string ErrorDeletingMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingMSG", resourceCulture);
            }
        }
        
        internal static string TeamDeletedMSG {
            get {
                return ResourceManager.GetString("TeamDeletedMSG", resourceCulture);
            }
        }
        
        internal static string EditTeam {
            get {
                return ResourceManager.GetString("EditTeam", resourceCulture);
            }
        }
        
        internal static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        internal static string ErrorAddingTeamMsg {
            get {
                return ResourceManager.GetString("ErrorAddingTeamMsg", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteThisProfileMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisProfileMSG", resourceCulture);
            }
        }
        
        internal static string ProfileDeletedMSG {
            get {
                return ResourceManager.GetString("ProfileDeletedMSG", resourceCulture);
            }
        }
        
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        internal static string ErrorCreatingRoleMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingRoleMSG", resourceCulture);
            }
        }
        
        internal static string ErroAddingTeamMSG {
            get {
                return ResourceManager.GetString("ErroAddingTeamMSG", resourceCulture);
            }
        }
        
        internal static string RolePermissions {
            get {
                return ResourceManager.GetString("RolePermissions", resourceCulture);
            }
        }
        
        internal static string ProfileSavedMSG {
            get {
                return ResourceManager.GetString("ProfileSavedMSG", resourceCulture);
            }
        }
        
        internal static string Vulnerabilities {
            get {
                return ResourceManager.GetString("Vulnerabilities", resourceCulture);
            }
        }
        
        internal static string TeamSavedMSG {
            get {
                return ResourceManager.GetString("TeamSavedMSG", resourceCulture);
            }
        }
        
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        internal static string FirstDetection {
            get {
                return ResourceManager.GetString("FirstDetection", resourceCulture);
            }
        }
        
        internal static string LastDetection {
            get {
                return ResourceManager.GetString("LastDetection", resourceCulture);
            }
        }
        
        internal static string DetectionCount {
            get {
                return ResourceManager.GetString("DetectionCount", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        internal static string Analyst {
            get {
                return ResourceManager.GetString("Analyst", resourceCulture);
            }
        }
        
        internal static string FixTeam {
            get {
                return ResourceManager.GetString("FixTeam", resourceCulture);
            }
        }
        
        internal static string TeamResponsible {
            get {
                return ResourceManager.GetString("TeamResponsible", resourceCulture);
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string Vulnerability {
            get {
                return ResourceManager.GetString("Vulnerability", resourceCulture);
            }
        }
        
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        internal static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        internal static string RiskFilter {
            get {
                return ResourceManager.GetString("RiskFilter", resourceCulture);
            }
        }
        
        internal static string PleaseSelectAtLeastOneRiskMSG {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneRiskMSG", resourceCulture);
            }
        }
        
        internal static string ErrorSavingVulnerabilityMSG {
            get {
                return ResourceManager.GetString("ErrorSavingVulnerabilityMSG", resourceCulture);
            }
        }
        
        internal static string PleaseEnterAValidIPMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValidIPMSG", resourceCulture);
            }
        }
        
        internal static string PleaseEnterAValidFqdnMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValidFqdnMSG", resourceCulture);
            }
        }
        
        internal static string ErrorSavingHostMSG {
            get {
                return ResourceManager.GetString("ErrorSavingHostMSG", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string PleaseSelectAVulnerabilityMSG {
            get {
                return ResourceManager.GetString("PleaseSelectAVulnerabilityMSG", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteVulnerabilityMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteVulnerabilityMSG", resourceCulture);
            }
        }
        
        internal static string ErrorDeletingVulnerabilityMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingVulnerabilityMSG", resourceCulture);
            }
        }
        
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Days_since_last_review {
            get {
                return ResourceManager.GetString("Days since last review", resourceCulture);
            }
        }
        
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        internal static string ReasonForRejection {
            get {
                return ResourceManager.GetString("ReasonForRejection", resourceCulture);
            }
        }
        
        internal static string RequestFix {
            get {
                return ResourceManager.GetString("RequestFix", resourceCulture);
            }
        }
        
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        internal static string Insignificant {
            get {
                return ResourceManager.GetString("Insignificant", resourceCulture);
            }
        }
        
        internal static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        internal static string FinalStatus {
            get {
                return ResourceManager.GetString("FinalStatus", resourceCulture);
            }
        }
        
        internal static string Prioritize {
            get {
                return ResourceManager.GetString("Prioritize", resourceCulture);
            }
        }
        
        internal static string ContributingRisk {
            get {
                return ResourceManager.GetString("ContributingRisk", resourceCulture);
            }
        }
        
        internal static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        internal static string Hosts {
            get {
                return ResourceManager.GetString("Hosts", resourceCulture);
            }
        }
        
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        internal static string ResponsibleTeam {
            get {
                return ResourceManager.GetString("ResponsibleTeam", resourceCulture);
            }
        }
        
        internal static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteThisHostMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisHostMSG", resourceCulture);
            }
        }
        
        internal static string PleaseEnterAValidValueMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueMSG", resourceCulture);
            }
        }
        
        internal static string IgnoreNegligible {
            get {
                return ResourceManager.GetString("IgnoreNegligible", resourceCulture);
            }
        }
        
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        internal static string HideFilter {
            get {
                return ResourceManager.GetString("HideFilter", resourceCulture);
            }
        }
        
        internal static string ImportedVulnerabilities {
            get {
                return ResourceManager.GetString("ImportedVulnerabilities", resourceCulture);
            }
        }
        
        internal static string PleaseAddARiskToTheVulnerabilityMSG {
            get {
                return ResourceManager.GetString("PleaseAddARiskToTheVulnerabilityMSG", resourceCulture);
            }
        }
        
        internal static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        internal static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        internal static string Importsources {
            get {
                return ResourceManager.GetString("Importsources", resourceCulture);
            }
        }
        
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        internal static string InvalidFilter {
            get {
                return ResourceManager.GetString("InvalidFilter", resourceCulture);
            }
        }
        
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        internal static string SystemConfigurations {
            get {
                return ResourceManager.GetString("SystemConfigurations", resourceCulture);
            }
        }
        
        internal static string BackupPassword {
            get {
                return ResourceManager.GetString("BackupPassword", resourceCulture);
            }
        }
        
        internal static string ConfigurationsSaved {
            get {
                return ResourceManager.GetString("ConfigurationsSaved", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        internal static string ConfirmationInvalid {
            get {
                return ResourceManager.GetString("ConfirmationInvalid", resourceCulture);
            }
        }
        
        internal static string ErrorChangingPasswordMSG {
            get {
                return ResourceManager.GetString("ErrorChangingPasswordMSG", resourceCulture);
            }
        }
        
        internal static string Impact_vs_Probability {
            get {
                return ResourceManager.GetString("Impact vs Probability", resourceCulture);
            }
        }
        
        internal static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        internal static string Unlikely {
            get {
                return ResourceManager.GetString("Unlikely", resourceCulture);
            }
        }
        
        internal static string Believable {
            get {
                return ResourceManager.GetString("Believable", resourceCulture);
            }
        }
        
        internal static string Likely {
            get {
                return ResourceManager.GetString("Likely", resourceCulture);
            }
        }
        
        internal static string Almost_Certain {
            get {
                return ResourceManager.GetString("Almost Certain", resourceCulture);
            }
        }
        
        internal static string application {
            get {
                return ResourceManager.GetString("application", resourceCulture);
            }
        }
        
        internal static string applicationModule {
            get {
                return ResourceManager.GetString("applicationModule", resourceCulture);
            }
        }
        
        internal static string AssessmentsRuns {
            get {
                return ResourceManager.GetString("AssessmentsRuns", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string NewAssessmentRun {
            get {
                return ResourceManager.GetString("NewAssessmentRun", resourceCulture);
            }
        }
        
        internal static string EditAssessmentRun {
            get {
                return ResourceManager.GetString("EditAssessmentRun", resourceCulture);
            }
        }
        
        internal static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        internal static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        internal static string RunDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("RunDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        internal static string ConfirmCommitMSG {
            get {
                return ResourceManager.GetString("ConfirmCommitMSG", resourceCulture);
            }
        }
        
        internal static string ErrorCreatingVulnerabilityMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingVulnerabilityMSG", resourceCulture);
            }
        }
        
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        internal static string VulnerabilitiesCreatedMSG {
            get {
                return ResourceManager.GetString("VulnerabilitiesCreatedMSG", resourceCulture);
            }
        }
        
        internal static string Entities_Risks {
            get {
                return ResourceManager.GetString("Entities Risks", resourceCulture);
            }
        }
        
        internal static string ParentEntity {
            get {
                return ResourceManager.GetString("ParentEntity", resourceCulture);
            }
        }
        
        internal static string TotalRiskRelatedToEntity {
            get {
                return ResourceManager.GetString("TotalRiskRelatedToEntity", resourceCulture);
            }
        }
        
        internal static string File_Reports {
            get {
                return ResourceManager.GetString("File Reports", resourceCulture);
            }
        }
        
        internal static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        internal static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        internal static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        internal static string DetailedEntitiesRisks {
            get {
                return ResourceManager.GetString("DetailedEntitiesRisks", resourceCulture);
            }
        }
        
        internal static string ReportDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("ReportDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        internal static string ErrorDeletingReportMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingReportMSG", resourceCulture);
            }
        }
        
        internal static string ErrorUpdatingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorUpdatingAssessmentMSG", resourceCulture);
            }
        }
        
        internal static string StrSolution {
            get {
                return ResourceManager.GetString("StrSolution", resourceCulture);
            }
        }
        
        internal static string ExploitAvailable {
            get {
                return ResourceManager.GetString("ExploitAvailable", resourceCulture);
            }
        }
        
        internal static string ThreatIntensity {
            get {
                return ResourceManager.GetString("ThreatIntensity", resourceCulture);
            }
        }
        
        internal static string ThreatRecency {
            get {
                return ResourceManager.GetString("ThreatRecency", resourceCulture);
            }
        }
        
        internal static string ThreatSources {
            get {
                return ResourceManager.GetString("ThreatSources", resourceCulture);
            }
        }
        
        internal static string VulnerabilityPublicationDate {
            get {
                return ResourceManager.GetString("VulnerabilityPublicationDate", resourceCulture);
            }
        }
        
        internal static string PatchPublicationDate {
            get {
                return ResourceManager.GetString("PatchPublicationDate", resourceCulture);
            }
        }
        
        internal static string TopCount {
            get {
                return ResourceManager.GetString("TopCount", resourceCulture);
            }
        }
        
        internal static string HostVulnerabilityPrioritization {
            get {
                return ResourceManager.GetString("HostVulnerabilityPrioritization", resourceCulture);
            }
        }
        
        internal static string Application_2 {
            get {
                return ResourceManager.GetString("Application_2", resourceCulture);
            }
        }
        
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        internal static string ImportUploadedAndStarted {
            get {
                return ResourceManager.GetString("ImportUploadedAndStarted", resourceCulture);
            }
        }
        
        internal static string Vulnerability_Fix_Request {
            get {
                return ResourceManager.GetString("Vulnerability Fix Request", resourceCulture);
            }
        }
        
        internal static string Communication_Type {
            get {
                return ResourceManager.GetString("Communication Type", resourceCulture);
            }
        }
        
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
    }
}
