//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUIClient.Resources.Localization.en-US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a document to add..
        /// </summary>
        internal static string AddDocumentMSG {
            get {
                return ResourceManager.GetString("AddDocumentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer alreay exists.
        /// </summary>
        internal static string AnswerAlreadyExistsMSG {
            get {
                return ResourceManager.GetString("AnswerAlreadyExistsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Application.
        /// </summary>
        internal static string ApplicationMN {
            get {
                return ResourceManager.GetString("ApplicationMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this profile?.
        /// </summary>
        internal static string AreYouSureToDeleteThisProfileMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisProfileMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are your sure you want to delete this team?.
        /// </summary>
        internal static string AreYouSureToDeleteThisTeamMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisTeamMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected user?.
        /// </summary>
        internal static string AreYouSureToDeleteThisUserMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisUserMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteMSG {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        internal static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assessment name alreay exists..
        /// </summary>
        internal static string AssessmentNameExistsMSG {
            get {
                return ResourceManager.GetString("AssessmentNameExistsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assessment name is invalid.
        /// </summary>
        internal static string AssessmentNameInvalidMSG {
            get {
                return ResourceManager.GetString("AssessmentNameInvalidMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessments.
        /// </summary>
        internal static string Assessments {
            get {
                return ResourceManager.GetString("Assessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business process.
        /// </summary>
        internal static string businessProcess {
            get {
                return ResourceManager.GetString("businessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean all.
        /// </summary>
        internal static string CleanAll {
            get {
                return ResourceManager.GetString("CleanAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to approve the client..
        /// </summary>
        internal static string ClientApproveErrorMSG {
            get {
                return ResourceManager.GetString("ClientApproveErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete that client?..
        /// </summary>
        internal static string ClientDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("ClientDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to process the client rejection..
        /// </summary>
        internal static string ClientRejectErrorMSG {
            get {
                return ResourceManager.GetString("ClientRejectErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close risk.
        /// </summary>
        internal static string CloseRisk {
            get {
                return ResourceManager.GetString("CloseRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you shure? This will delete completly the assignment: .
        /// </summary>
        internal static string ConfirmDeleteAssessmentMSG {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssessmentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you shure you want to delete the assessment question: .
        /// </summary>
        internal static string ConfirmDeleteAssessmentQuestionMSG {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssessmentQuestionMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk by Control.
        /// </summary>
        internal static string ControlRisk {
            get {
                return ResourceManager.GetString("ControlRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Control Statistics.
        /// </summary>
        internal static string ControlStatistics {
            get {
                return ResourceManager.GetString("ControlStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost vs Risk.
        /// </summary>
        internal static string Cost_vs_Risk {
            get {
                return ResourceManager.GetString("Cost vs Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Entity.
        /// </summary>
        internal static string CreateEntity {
            get {
                return ResourceManager.GetString("CreateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Maturity.
        /// </summary>
        internal static string DesiredMaturity {
            get {
                return ResourceManager.GetString("DesiredMaturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entity.
        /// </summary>
        internal static string EditEntity {
            get {
                return ResourceManager.GetString("EditEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit team.
        /// </summary>
        internal static string EditTeam {
            get {
                return ResourceManager.GetString("EditTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effort.
        /// </summary>
        internal static string Effort {
            get {
                return ResourceManager.GetString("Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrer a valid email..
        /// </summary>
        internal static string EnterAValidEmailMSG {
            get {
                return ResourceManager.GetString("EnterAValidEmailMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        internal static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity saved successfully..
        /// </summary>
        internal static string EntitySavedSuccessMSG {
            get {
                return ResourceManager.GetString("EntitySavedSuccessMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding team.
        /// </summary>
        internal static string ErroAddingTeamMSG {
            get {
                return ResourceManager.GetString("ErroAddingTeamMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding new team..
        /// </summary>
        internal static string ErrorAddingTeamMsg {
            get {
                return ResourceManager.GetString("ErrorAddingTeamMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating assessment..
        /// </summary>
        internal static string ErrorCreatingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingAssessmentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating entity..
        /// </summary>
        internal static string ErrorCreatingEntityMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingEntityMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating or saving a risk..
        /// </summary>
        internal static string ErrorCreatingRiskMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingRiskMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new profile.
        /// </summary>
        internal static string ErrorCreatingRoleMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingRoleMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting selected assessment..
        /// </summary>
        internal static string ErrorDeletingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingAssessmentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting assessment question..
        /// </summary>
        internal static string ErrorDeletingAssessmentQuestionMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingAssessmentQuestionMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro on delete operation.
        /// </summary>
        internal static string ErrorDeletingMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading review.
        /// </summary>
        internal static string ErrorLoadingReviewMSG {
            get {
                return ResourceManager.GetString("ErrorLoadingReviewMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating or saving a mitigation..
        /// </summary>
        internal static string ErrorMitigationMSG {
            get {
                return ResourceManager.GetString("ErrorMitigationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening browser: .
        /// </summary>
        internal static string ErrorOpeningExternalBrowserMSG {
            get {
                return ResourceManager.GetString("ErrorOpeningExternalBrowserMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving the answers..
        /// </summary>
        internal static string ErrorSavingAnswersMSG {
            get {
                return ResourceManager.GetString("ErrorSavingAnswersMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A error occurred while saving the question..
        /// </summary>
        internal static string ErrorSavingQuestionMSG {
            get {
                return ResourceManager.GetString("ErrorSavingQuestionMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        internal static string ExitMN {
            get {
                return ResourceManager.GetString("ExitMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you shure you want to delete the selected file?.
        /// </summary>
        internal static string FileDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("FileDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file..
        /// </summary>
        internal static string FileDeletionErrorMSG {
            get {
                return ResourceManager.GetString("FileDeletionErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first select a user..
        /// </summary>
        internal static string FirstSelectAUserMSG {
            get {
                return ResourceManager.GetString("FirstSelectAUserMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact.
        /// </summary>
        internal static string Impact {
            get {
                return ResourceManager.GetString("Impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Main Organization.
        /// </summary>
        internal static string Is_Main_Organization {
            get {
                return ResourceManager.GetString("Is Main Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Password Change.
        /// </summary>
        internal static string LastPasswordChange {
            get {
                return ResourceManager.GetString("LastPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Review.
        /// </summary>
        internal static string LastReview {
            get {
                return ResourceManager.GetString("LastReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Account.
        /// </summary>
        internal static string LoggedAccount {
            get {
                return ResourceManager.GetString("LoggedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You login process failed..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout and Quit.
        /// </summary>
        internal static string LogoutQuit {
            get {
                return ResourceManager.GetString("LogoutQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Organization.
        /// </summary>
        internal static string Main_Organization {
            get {
                return ResourceManager.GetString("Main Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Reviewed.
        /// </summary>
        internal static string ManagerReviewed {
            get {
                return ResourceManager.GetString("ManagerReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturity.
        /// </summary>
        internal static string Maturity {
            get {
                return ResourceManager.GetString("Maturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Risk.
        /// </summary>
        internal static string Max_Risk {
            get {
                return ResourceManager.GetString("Max Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Risk.
        /// </summary>
        internal static string Min_Risk {
            get {
                return ResourceManager.GetString("Min Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation.
        /// </summary>
        internal static string Mitigation {
            get {
                return ResourceManager.GetString("Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation cost.
        /// </summary>
        internal static string MitigationCost {
            get {
                return ResourceManager.GetString("MitigationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation effort.
        /// </summary>
        internal static string MitigationEffort {
            get {
                return ResourceManager.GetString("MitigationEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation not planned..
        /// </summary>
        internal static string MitigationNotPlannedMSG {
            get {
                return ResourceManager.GetString("MitigationNotPlannedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation owner.
        /// </summary>
        internal static string MitigationOwner {
            get {
                return ResourceManager.GetString("MitigationOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation percent.
        /// </summary>
        internal static string MitigationPercent {
            get {
                return ResourceManager.GetString("MitigationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation Planned.
        /// </summary>
        internal static string MitigationPlanned {
            get {
                return ResourceManager.GetString("MitigationPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation team.
        /// </summary>
        internal static string MitigationTeam {
            get {
                return ResourceManager.GetString("MitigationTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetRisk Version.
        /// </summary>
        internal static string NetRiskVersionMGS {
            get {
                return ResourceManager.GetString("NetRiskVersionMGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Review.
        /// </summary>
        internal static string NextReview {
            get {
                return ResourceManager.GetString("NextReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        internal static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has not being registred. Pelase ask your administrator to authorize the application with ID:.
        /// </summary>
        internal static string NoRegistrationMSG {
            get {
                return ResourceManager.GetString("NoRegistrationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registratin is not accepted.
        /// </summary>
        internal static string NotAccepted {
            get {
                return ResourceManager.GetString("NotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not implemented yet..
        /// </summary>
        internal static string NotImplementedMSG {
            get {
                return ResourceManager.GetString("NotImplementedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Employees.
        /// </summary>
        internal static string Number_Of_Employees {
            get {
                return ResourceManager.GetString("Number Of Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational System.
        /// </summary>
        internal static string OperationalSystem {
            get {
                return ResourceManager.GetString("OperationalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization.
        /// </summary>
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit.
        /// </summary>
        internal static string Organization_Unit {
            get {
                return ResourceManager.GetString("Organization Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization unit.
        /// </summary>
        internal static string organizationUnit {
            get {
                return ResourceManager.GetString("organizationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to person.
        /// </summary>
        internal static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Mitigation.
        /// </summary>
        internal static string PlanMitigation {
            get {
                return ResourceManager.GetString("PlanMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Mitigation Date.
        /// </summary>
        internal static string PlannedDate {
            get {
                return ResourceManager.GetString("PlannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Strategy.
        /// </summary>
        internal static string PlanningStrategy {
            get {
                return ResourceManager.GetString("PlanningStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the erros before saving..
        /// </summary>
        internal static string PleaseCorrectTheErrorsMSG {
            get {
                return ResourceManager.GetString("PleaseCorrectTheErrorsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value..
        /// </summary>
        internal static string PleaseEnterAValueMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValueMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one item..
        /// </summary>
        internal static string PleaseSelectAnItemMSG {
            get {
                return ResourceManager.GetString("PleaseSelectAnItemMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one value..
        /// </summary>
        internal static string PleaseSelectOneMSG {
            get {
                return ResourceManager.GetString("PleaseSelectOneMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability.
        /// </summary>
        internal static string Probability {
            get {
                return ResourceManager.GetString("Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile deleted..
        /// </summary>
        internal static string ProfileDeletedMSG {
            get {
                return ResourceManager.GetString("ProfileDeletedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Saved.
        /// </summary>
        internal static string ProfileSavedMSG {
            get {
                return ResourceManager.GetString("ProfileSavedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected.
        /// </summary>
        internal static string Projected {
            get {
                return ResourceManager.GetString("Projected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question already exists..
        /// </summary>
        internal static string QuestionAlreadyExistsMSG {
            get {
                return ResourceManager.GetString("QuestionAlreadyExistsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question does not exists..
        /// </summary>
        internal static string QuestionDoesNotExistsMSG {
            get {
                return ResourceManager.GetString("QuestionDoesNotExistsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error tring to register your application with the server..
        /// </summary>
        internal static string RegistrationErrorMSG {
            get {
                return ResourceManager.GetString("RegistrationErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your app registration was not yet accepted by an administrator. ID: .
        /// </summary>
        internal static string RegistrationNotAcceptedMSG {
            get {
                return ResourceManager.GetString("RegistrationNotAcceptedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing yourself from admin is dangerous are you shure you want to continue?.
        /// </summary>
        internal static string RemovingYourAdminRightsMSG {
            get {
                return ResourceManager.GetString("RemovingYourAdminRightsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Decision.
        /// </summary>
        internal static string ReviewDecision {
            get {
                return ResourceManager.GetString("ReviewDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review not done.
        /// </summary>
        internal static string ReviewNotDone {
            get {
                return ResourceManager.GetString("ReviewNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        internal static string Risk {
            get {
                return ResourceManager.GetString("Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Review.
        /// </summary>
        internal static string Risk_Review {
            get {
                return ResourceManager.GetString("Risk Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk review by time.
        /// </summary>
        internal static string Risk_review_by_time {
            get {
                return ResourceManager.GetString("Risk review by time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while closing risk..
        /// </summary>
        internal static string RiskClosingErrorMSG {
            get {
                return ResourceManager.GetString("RiskClosingErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you shure you want to delete the selected risk?.
        /// </summary>
        internal static string RiskDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("RiskDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk must have a subject..
        /// </summary>
        internal static string RiskMustHaveASubjectMSG {
            get {
                return ResourceManager.GetString("RiskMustHaveASubjectMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks.
        /// </summary>
        internal static string Risks {
            get {
                return ResourceManager.GetString("Risks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks over time.
        /// </summary>
        internal static string RisksOverTime {
            get {
                return ResourceManager.GetString("RisksOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Type.
        /// </summary>
        internal static string RiskType {
            get {
                return ResourceManager.GetString("RiskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Permissions.
        /// </summary>
        internal static string RolePermissions {
            get {
                return ResourceManager.GetString("RolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SAML authentication attempt runned out of time.
        /// </summary>
        internal static string SAMLAuthenticationTimeoutMSG {
            get {
                return ResourceManager.GetString("SAMLAuthenticationTimeoutMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save dcument as ....
        /// </summary>
        internal static string SaveDocumentMSG {
            get {
                return ResourceManager.GetString("SaveDocumentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved risk with success..
        /// </summary>
        internal static string SaveOkMSG {
            get {
                return ResourceManager.GetString("SaveOkMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring.
        /// </summary>
        internal static string Scoring {
            get {
                return ResourceManager.GetString("Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomendation.
        /// </summary>
        internal static string SecurityRecommendation {
            get {
                return ResourceManager.GetString("SecurityRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Requirements.
        /// </summary>
        internal static string SecurityRequirements {
            get {
                return ResourceManager.GetString("SecurityRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your authentication method..
        /// </summary>
        internal static string SelectAuthenticationMSG {
            get {
                return ResourceManager.GetString("SelectAuthenticationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a risk before tring to edit.
        /// </summary>
        internal static string SelectRiskDeleteMSG {
            get {
                return ResourceManager.GetString("SelectRiskDeleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please seelct a risk before deleting..
        /// </summary>
        internal static string SelectRiskMSG {
            get {
                return ResourceManager.GetString("SelectRiskMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Filter.
        /// </summary>
        internal static string StatusFilter {
            get {
                return ResourceManager.GetString("StatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation owner.
        /// </summary>
        internal static string StrMitigationOwner {
            get {
                return ResourceManager.GetString("StrMitigationOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected.
        /// </summary>
        internal static string StrProjected {
            get {
                return ResourceManager.GetString("StrProjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Panel.
        /// </summary>
        internal static string StrRiskPanel {
            get {
                return ResourceManager.GetString("StrRiskPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Date.
        /// </summary>
        internal static string SubmissionDate {
            get {
                return ResourceManager.GetString("SubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted by.
        /// </summary>
        internal static string SubmittedBy {
            get {
                return ResourceManager.GetString("SubmittedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Sys {
            get {
                return ResourceManager.GetString("Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Deleted.
        /// </summary>
        internal static string TeamDeletedMSG {
            get {
                return ResourceManager.GetString("TeamDeletedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        internal static string TeamMembers {
            get {
                return ResourceManager.GetString("TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        internal static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team saved!.
        /// </summary>
        internal static string TeamSavedMSG {
            get {
                return ResourceManager.GetString("TeamSavedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error:.
        /// </summary>
        internal static string UnexpectedErrorMSG {
            get {
                return ResourceManager.GetString("UnexpectedErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new upgrade is avaliable and the aplication needs to restart before proceeding..
        /// </summary>
        internal static string UpgradeNeededMSG {
            get {
                return ResourceManager.GetString("UpgradeNeededMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be unique..
        /// </summary>
        internal static string UsernameMustBeUniqueMSG {
            get {
                return ResourceManager.GetString("UsernameMustBeUniqueMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilities.
        /// </summary>
        internal static string Vulnerabilities {
            get {
                return ResourceManager.GetString("Vulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the SRGUI Client..
        /// </summary>
        internal static string WelcomeMSG {
            get {
                return ResourceManager.GetString("WelcomeMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete yourself..
        /// </summary>
        internal static string YouCannotDeleteYourselfMSG {
            get {
                return ResourceManager.GetString("YouCannotDeleteYourselfMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot disable yourself. .
        /// </summary>
        internal static string YouCannotDisableYourselfMSG {
            get {
                return ResourceManager.GetString("YouCannotDisableYourselfMSG", resourceCulture);
            }
        }
    }
}
