//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUIClient.Resources.Localization.pt-BR", typeof(Localization_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um documento para adicionar..
        /// </summary>
        internal static string AddDocumentMSG {
            get {
                return ResourceManager.GetString("AddDocumentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administração.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analista.
        /// </summary>
        internal static string Analyst {
            get {
                return ResourceManager.GetString("Analyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resposta já existe.
        /// </summary>
        internal static string AnswerAlreadyExistsMSG {
            get {
                return ResourceManager.GetString("AnswerAlreadyExistsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respostas.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Aplicação.
        /// </summary>
        internal static string ApplicationMN {
            get {
                return ResourceManager.GetString("ApplicationMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este computador?.
        /// </summary>
        internal static string AreYouSureToDeleteThisHostMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisHostMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este perfil?.
        /// </summary>
        internal static string AreYouSureToDeleteThisProfileMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisProfileMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este time?.
        /// </summary>
        internal static string AreYouSureToDeleteThisTeamMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisTeamMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar o usuário selecionado?.
        /// </summary>
        internal static string AreYouSureToDeleteThisUserMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteThisUserMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem ceteza que deseja apagar a vulnerabilidade:.
        /// </summary>
        internal static string AreYouSureToDeleteVulnerabilityMSG {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteVulnerabilityMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteMSG {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levantamento.
        /// </summary>
        internal static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do levantamento já existe..
        /// </summary>
        internal static string AssessmentNameExistsMSG {
            get {
                return ResourceManager.GetString("AssessmentNameExistsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do levantamento é inválido.
        /// </summary>
        internal static string AssessmentNameInvalidMSG {
            get {
                return ResourceManager.GetString("AssessmentNameInvalidMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levantamentos.
        /// </summary>
        internal static string Assessments {
            get {
                return ResourceManager.GetString("Assessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponíveis.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processo de negócio.
        /// </summary>
        internal static string businessProcess {
            get {
                return ResourceManager.GetString("businessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abortar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar todos.
        /// </summary>
        internal static string CleanAll {
            get {
                return ResourceManager.GetString("CleanAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na tentativa de aprovar o cliente..
        /// </summary>
        internal static string ClientApproveErrorMSG {
            get {
                return ResourceManager.GetString("ClientApproveErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este cliente?.
        /// </summary>
        internal static string ClientDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("ClientDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na tentativa de processar a rejeição do cliente.
        /// </summary>
        internal static string ClientRejectErrorMSG {
            get {
                return ResourceManager.GetString("ClientRejectErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechado.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechamento.
        /// </summary>
        internal static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar risco.
        /// </summary>
        internal static string CloseRisk {
            get {
                return ResourceManager.GetString("CloseRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentários.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computador.
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza? Isto irá apagar completamente o levantamento: .
        /// </summary>
        internal static string ConfirmDeleteAssessmentMSG {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssessmentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar a pergunta do levantamento: .
        /// </summary>
        internal static string ConfirmDeleteAssessmentQuestionMSG {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssessmentQuestionMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco por contribuição.
        /// </summary>
        internal static string ContributingRisk {
            get {
                return ResourceManager.GetString("ContributingRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco por controle.
        /// </summary>
        internal static string ControlRisk {
            get {
                return ResourceManager.GetString("ControlRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatísticas dos controles de segurança.
        /// </summary>
        internal static string ControlStatistics {
            get {
                return ResourceManager.GetString("ControlStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custo.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custo vs Risco.
        /// </summary>
        internal static string Cost_vs_Risk {
            get {
                return ResourceManager.GetString("Cost vs Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Entidade.
        /// </summary>
        internal static string CreateEntity {
            get {
                return ResourceManager.GetString("CreateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crítico.
        /// </summary>
        internal static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias desde a ultima revisão.
        /// </summary>
        internal static string Days_since_last_review {
            get {
                return ResourceManager.GetString("Days since last review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturidade Desejada.
        /// </summary>
        internal static string DesiredMaturity {
            get {
                return ResourceManager.GetString("DesiredMaturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecções.
        /// </summary>
        internal static string DetectionCount {
            get {
                return ResourceManager.GetString("DetectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivos.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribuição.
        /// </summary>
        internal static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação.
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar entidade.
        /// </summary>
        internal static string EditEntity {
            get {
                return ResourceManager.GetString("EditEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar time.
        /// </summary>
        internal static string EditTeam {
            get {
                return ResourceManager.GetString("EditTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esforço.
        /// </summary>
        internal static string Effort {
            get {
                return ResourceManager.GetString("Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre com um e-mail válido..
        /// </summary>
        internal static string EnterAValidEmailMSG {
            get {
                return ResourceManager.GetString("EnterAValidEmailMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        internal static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade.
        /// </summary>
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade salva com sucesso..
        /// </summary>
        internal static string EntitySavedSuccessMSG {
            get {
                return ResourceManager.GetString("EntitySavedSuccessMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiente.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro adicionando time.
        /// </summary>
        internal static string ErroAddingTeamMSG {
            get {
                return ResourceManager.GetString("ErroAddingTeamMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro adicionando novo time..
        /// </summary>
        internal static string ErrorAddingTeamMsg {
            get {
                return ResourceManager.GetString("ErrorAddingTeamMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro criando levantamento..
        /// </summary>
        internal static string ErrorCreatingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingAssessmentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro criando entidade..
        /// </summary>
        internal static string ErrorCreatingEntityMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingEntityMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro criando ou atualizando um risco..
        /// </summary>
        internal static string ErrorCreatingRiskMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingRiskMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro criando novo perfil.
        /// </summary>
        internal static string ErrorCreatingRoleMSG {
            get {
                return ResourceManager.GetString("ErrorCreatingRoleMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro apagando o levantamento selecionado..
        /// </summary>
        internal static string ErrorDeletingAssessmentMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingAssessmentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro apagando a pergunta do levantamento..
        /// </summary>
        internal static string ErrorDeletingAssessmentQuestionMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingAssessmentQuestionMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na operação de apagar.
        /// </summary>
        internal static string ErrorDeletingMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro apagando vulnerabilidade.
        /// </summary>
        internal static string ErrorDeletingVulnerabilityMSG {
            get {
                return ResourceManager.GetString("ErrorDeletingVulnerabilityMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carregando a revisão.
        /// </summary>
        internal static string ErrorLoadingReviewMSG {
            get {
                return ResourceManager.GetString("ErrorLoadingReviewMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro criando ou atualizando uma mitigação..
        /// </summary>
        internal static string ErrorMitigationMSG {
            get {
                return ResourceManager.GetString("ErrorMitigationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro abrindo o browser: .
        /// </summary>
        internal static string ErrorOpeningExternalBrowserMSG {
            get {
                return ResourceManager.GetString("ErrorOpeningExternalBrowserMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro salvando as respostas..
        /// </summary>
        internal static string ErrorSavingAnswersMSG {
            get {
                return ResourceManager.GetString("ErrorSavingAnswersMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro salvando computador.
        /// </summary>
        internal static string ErrorSavingHostMSG {
            get {
                return ResourceManager.GetString("ErrorSavingHostMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro ocorreu ao salvar a pergunta..
        /// </summary>
        internal static string ErrorSavingQuestionMSG {
            get {
                return ResourceManager.GetString("ErrorSavingQuestionMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro salvando vulnerabilidade..
        /// </summary>
        internal static string ErrorSavingVulnerabilityMSG {
            get {
                return ResourceManager.GetString("ErrorSavingVulnerabilityMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sair.
        /// </summary>
        internal static string ExitMN {
            get {
                return ResourceManager.GetString("ExitMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar o arquivo selecionado?.
        /// </summary>
        internal static string FileDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("FileDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro apagando o arquivo..
        /// </summary>
        internal static string FileDeletionErrorMSG {
            get {
                return ResourceManager.GetString("FileDeletionErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de arquivo.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Final.
        /// </summary>
        internal static string FinalStatus {
            get {
                return ResourceManager.GetString("FinalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeira Detecção.
        /// </summary>
        internal static string FirstDetection {
            get {
                return ResourceManager.GetString("FirstDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor primeiro selecione um usuário..
        /// </summary>
        internal static string FirstSelectAUserMSG {
            get {
                return ResourceManager.GetString("FirstSelectAUserMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time de Ajuste.
        /// </summary>
        internal static string FixTeam {
            get {
                return ResourceManager.GetString("FixTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Características.
        /// </summary>
        internal static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esconder Filtro.
        /// </summary>
        internal static string HideFilter {
            get {
                return ResourceManager.GetString("HideFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computador.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computadores.
        /// </summary>
        internal static string Hosts {
            get {
                return ResourceManager.GetString("Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingorar risco irrisório.
        /// </summary>
        internal static string IgnoreNegligible {
            get {
                return ResourceManager.GetString("IgnoreNegligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impacto.
        /// </summary>
        internal static string Impact {
            get {
                return ResourceManager.GetString("Impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizada importação de .
        /// </summary>
        internal static string ImportedVulnerabilities {
            get {
                return ResourceManager.GetString("ImportedVulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem dos dados.
        /// </summary>
        internal static string Importsources {
            get {
                return ResourceManager.GetString("Importsources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações.
        /// </summary>
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insignificante.
        /// </summary>
        internal static string Insignificant {
            get {
                return ResourceManager.GetString("Insignificant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro inválido.
        /// </summary>
        internal static string InvalidFilter {
            get {
                return ResourceManager.GetString("InvalidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organização Principal.
        /// </summary>
        internal static string Is_Main_Organization {
            get {
                return ResourceManager.GetString("Is Main Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Detecção.
        /// </summary>
        internal static string LastDetection {
            get {
                return ResourceManager.GetString("LastDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Login.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Troca de Senha.
        /// </summary>
        internal static string LastPasswordChange {
            get {
                return ResourceManager.GetString("LastPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Revisão.
        /// </summary>
        internal static string LastReview {
            get {
                return ResourceManager.GetString("LastReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trancado.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Usada.
        /// </summary>
        internal static string LoggedAccount {
            get {
                return ResourceManager.GetString("LoggedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu processo de entrada falhou..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descontectar e Fechar.
        /// </summary>
        internal static string LogoutQuit {
            get {
                return ResourceManager.GetString("LogoutQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixo.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máquina.
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organização Principal.
        /// </summary>
        internal static string Main_Organization {
            get {
                return ResourceManager.GetString("Main Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerente.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisado pelo gerente.
        /// </summary>
        internal static string ManagerReviewed {
            get {
                return ResourceManager.GetString("ManagerReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturidade.
        /// </summary>
        internal static string Maturity {
            get {
                return ResourceManager.GetString("Maturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco Max..
        /// </summary>
        internal static string Max_Risk {
            get {
                return ResourceManager.GetString("Max Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médio.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco Min..
        /// </summary>
        internal static string Min_Risk {
            get {
                return ResourceManager.GetString("Min Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigação.
        /// </summary>
        internal static string Mitigation {
            get {
                return ResourceManager.GetString("Mitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custo de mitigação.
        /// </summary>
        internal static string MitigationCost {
            get {
                return ResourceManager.GetString("MitigationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esforço de mitigação.
        /// </summary>
        internal static string MitigationEffort {
            get {
                return ResourceManager.GetString("MitigationEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigação não planejada.
        /// </summary>
        internal static string MitigationNotPlannedMSG {
            get {
                return ResourceManager.GetString("MitigationNotPlannedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável pela mitigação.
        /// </summary>
        internal static string MitigationOwner {
            get {
                return ResourceManager.GetString("MitigationOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual da mitigação.
        /// </summary>
        internal static string MitigationPercent {
            get {
                return ResourceManager.GetString("MitigationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigação Planejada.
        /// </summary>
        internal static string MitigationPlanned {
            get {
                return ResourceManager.GetString("MitigationPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time de mitigação.
        /// </summary>
        internal static string MitigationTeam {
            get {
                return ResourceManager.GetString("MitigationTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão do NetRisk.
        /// </summary>
        internal static string NetRiskVersionMGS {
            get {
                return ResourceManager.GetString("NetRiskVersionMGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próxima Revisão.
        /// </summary>
        internal static string NextReview {
            get {
                return ResourceManager.GetString("NextReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo Passo.
        /// </summary>
        internal static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua aplicação não foi registrada. Por favor solicite ao administrador que autorize a aplicação com o ID:.
        /// </summary>
        internal static string NoRegistrationMSG {
            get {
                return ResourceManager.GetString("NoRegistrationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu registro não foi aceito.
        /// </summary>
        internal static string NotAccepted {
            get {
                return ResourceManager.GetString("NotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este método ainda não foi implementado..
        /// </summary>
        internal static string NotImplementedMSG {
            get {
                return ResourceManager.GetString("NotImplementedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de funcionários.
        /// </summary>
        internal static string Number_Of_Employees {
            get {
                return ResourceManager.GetString("Number Of Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Números.
        /// </summary>
        internal static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aberto.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema Operacional.
        /// </summary>
        internal static string OperatingSystem {
            get {
                return ResourceManager.GetString("OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema Operacional.
        /// </summary>
        internal static string OperationalSystem {
            get {
                return ResourceManager.GetString("OperationalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organização.
        /// </summary>
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Organizacional.
        /// </summary>
        internal static string Organization_Unit {
            get {
                return ResourceManager.GetString("Organization Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unidadate organizacional.
        /// </summary>
        internal static string organizationUnit {
            get {
                return ResourceManager.GetString("organizationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dono.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predecessora.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissões.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pessoa.
        /// </summary>
        internal static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Telefone.
        /// </summary>
        internal static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planejar Mitigação.
        /// </summary>
        internal static string PlanMitigation {
            get {
                return ResourceManager.GetString("PlanMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data  Planejada para Mitigação.
        /// </summary>
        internal static string PlannedDate {
            get {
                return ResourceManager.GetString("PlannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estratégia planejada.
        /// </summary>
        internal static string PlanningStrategy {
            get {
                return ResourceManager.GetString("PlanningStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor associe um risco à vulnerabilidade..
        /// </summary>
        internal static string PleaseAddARiskToTheVulnerabilityMSG {
            get {
                return ResourceManager.GetString("PleaseAddARiskToTheVulnerabilityMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor corrija os erros antes de salvar..
        /// </summary>
        internal static string PleaseCorrectTheErrorsMSG {
            get {
                return ResourceManager.GetString("PleaseCorrectTheErrorsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor entre com um FQDN válido.
        /// </summary>
        internal static string PleaseEnterAValidFqdnMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValidFqdnMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor entre com um endereço IP válido.
        /// </summary>
        internal static string PleaseEnterAValidIPMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValidIPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor entre com um valor válido.
        /// </summary>
        internal static string PleaseEnterAValidValueMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValueMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor entre um valor..
        /// </summary>
        internal static string PleaseEnterAValueMSG {
            get {
                return ResourceManager.GetString("PleaseEnterAValueMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor slecione um item..
        /// </summary>
        internal static string PleaseSelectAnItemMSG {
            get {
                return ResourceManager.GetString("PleaseSelectAnItemMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione pelo menos um risco..
        /// </summary>
        internal static string PleaseSelectAtLeastOneRiskMSG {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneRiskMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione uma vulnerabilidade.
        /// </summary>
        internal static string PleaseSelectAVulnerabilityMSG {
            get {
                return ResourceManager.GetString("PleaseSelectAVulnerabilityMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione um valor..
        /// </summary>
        internal static string PleaseSelectOneMSG {
            get {
                return ResourceManager.GetString("PleaseSelectOneMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porta.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorizar.
        /// </summary>
        internal static string Prioritize {
            get {
                return ResourceManager.GetString("Prioritize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probabilidade.
        /// </summary>
        internal static string Probability {
            get {
                return ResourceManager.GetString("Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil Apagado..
        /// </summary>
        internal static string ProfileDeletedMSG {
            get {
                return ResourceManager.GetString("ProfileDeletedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do perfil.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfis.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil Salvo.
        /// </summary>
        internal static string ProfileSavedMSG {
            get {
                return ResourceManager.GetString("ProfileSavedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado.
        /// </summary>
        internal static string Projected {
            get {
                return ResourceManager.GetString("Projected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pergunta já existe..
        /// </summary>
        internal static string QuestionAlreadyExistsMSG {
            get {
                return ResourceManager.GetString("QuestionAlreadyExistsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa pergunta não existe..
        /// </summary>
        internal static string QuestionDoesNotExistsMSG {
            get {
                return ResourceManager.GetString("QuestionDoesNotExistsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perguntas.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão para rejeição.
        /// </summary>
        internal static string ReasonForRejection {
            get {
                return ResourceManager.GetString("ReasonForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Registro.
        /// </summary>
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro tentando registrar a sua aplicação com o servidor..
        /// </summary>
        internal static string RegistrationErrorMSG {
            get {
                return ResourceManager.GetString("RegistrationErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro do seu aplicativo ainda não foi aceito por um administrador. ID:.
        /// </summary>
        internal static string RegistrationNotAcceptedMSG {
            get {
                return ResourceManager.GetString("RegistrationNotAcceptedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeitar.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recarregar.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover a sua permisão de admin é perigoso, deseja mesmo continuar?.
        /// </summary>
        internal static string RemovingYourAdminRightsMSG {
            get {
                return ResourceManager.GetString("RemovingYourAdminRightsMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Ajuste.
        /// </summary>
        internal static string RequestFix {
            get {
                return ResourceManager.GetString("RequestFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        internal static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Responsável.
        /// </summary>
        internal static string ResponsibleTeam {
            get {
                return ResourceManager.GetString("ResponsibleTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de revisão.
        /// </summary>
        internal static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado da revisão.
        /// </summary>
        internal static string ReviewDecision {
            get {
                return ResourceManager.GetString("ReviewDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisão não feita.
        /// </summary>
        internal static string ReviewNotDone {
            get {
                return ResourceManager.GetString("ReviewNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco.
        /// </summary>
        internal static string Risk {
            get {
                return ResourceManager.GetString("Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisão do Risco.
        /// </summary>
        internal static string Risk_Review {
            get {
                return ResourceManager.GetString("Risk Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisão do risco por tempo.
        /// </summary>
        internal static string Risk_review_by_time {
            get {
                return ResourceManager.GetString("Risk review by time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro ocorreu enquanto fechava o risco..
        /// </summary>
        internal static string RiskClosingErrorMSG {
            get {
                return ResourceManager.GetString("RiskClosingErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar o risco selecionado?.
        /// </summary>
        internal static string RiskDeleteConfirmationMSG {
            get {
                return ResourceManager.GetString("RiskDeleteConfirmationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro de Risco.
        /// </summary>
        internal static string RiskFilter {
            get {
                return ResourceManager.GetString("RiskFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco precisa ter um assunto..
        /// </summary>
        internal static string RiskMustHaveASubjectMSG {
            get {
                return ResourceManager.GetString("RiskMustHaveASubjectMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riscos.
        /// </summary>
        internal static string Risks {
            get {
                return ResourceManager.GetString("Risks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riscos através do tempo.
        /// </summary>
        internal static string RisksOverTime {
            get {
                return ResourceManager.GetString("RisksOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Risco.
        /// </summary>
        internal static string RiskType {
            get {
                return ResourceManager.GetString("RiskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissiões do Perfil.
        /// </summary>
        internal static string RolePermissions {
            get {
                return ResourceManager.GetString("RolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tentativa de autenticação SAML expirou..
        /// </summary>
        internal static string SAMLAuthenticationTimeoutMSG {
            get {
                return ResourceManager.GetString("SAMLAuthenticationTimeoutMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar documento como ....
        /// </summary>
        internal static string SaveDocumentMSG {
            get {
                return ResourceManager.GetString("SaveDocumentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risco salvo com sucesso..
        /// </summary>
        internal static string SaveOkMSG {
            get {
                return ResourceManager.GetString("SaveOkMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação.
        /// </summary>
        internal static string Scoring {
            get {
                return ResourceManager.GetString("Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recomendação.
        /// </summary>
        internal static string SecurityRecommendation {
            get {
                return ResourceManager.GetString("SecurityRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisitos de Segurança.
        /// </summary>
        internal static string SecurityRequirements {
            get {
                return ResourceManager.GetString("SecurityRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionar todos.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione o seu método de autenticação..
        /// </summary>
        internal static string SelectAuthenticationMSG {
            get {
                return ResourceManager.GetString("SelectAuthenticationMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionados.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione um risco antes de tentar apagá-lo..
        /// </summary>
        internal static string SelectRiskDeleteMSG {
            get {
                return ResourceManager.GetString("SelectRiskDeleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecione um risco antes de editar..
        /// </summary>
        internal static string SelectRiskMSG {
            get {
                return ResourceManager.GetString("SelectRiskMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solução.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro de estado.
        /// </summary>
        internal static string StatusFilter {
            get {
                return ResourceManager.GetString("StatusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estratégia.
        /// </summary>
        internal static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável pela mitigação.
        /// </summary>
        internal static string StrMitigationOwner {
            get {
                return ResourceManager.GetString("StrMitigationOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado.
        /// </summary>
        internal static string StrProjected {
            get {
                return ResourceManager.GetString("StrProjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel de Riscos.
        /// </summary>
        internal static string StrRiskPanel {
            get {
                return ResourceManager.GetString("StrRiskPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de criação.
        /// </summary>
        internal static string SubmissionDate {
            get {
                return ResourceManager.GetString("SubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviado por.
        /// </summary>
        internal static string SubmittedBy {
            get {
                return ResourceManager.GetString("SubmittedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        internal static string Sys {
            get {
                return ResourceManager.GetString("Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Apagado.
        /// </summary>
        internal static string TeamDeletedMSG {
            get {
                return ResourceManager.GetString("TeamDeletedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membros do Time.
        /// </summary>
        internal static string TeamMembers {
            get {
                return ResourceManager.GetString("TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do time.
        /// </summary>
        internal static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Responsável.
        /// </summary>
        internal static string TeamResponsible {
            get {
                return ResourceManager.GetString("TeamResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time salvo!.
        /// </summary>
        internal static string TeamSavedMSG {
            get {
                return ResourceManager.GetString("TeamSavedMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologias.
        /// </summary>
        internal static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologia.
        /// </summary>
        internal static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação total.
        /// </summary>
        internal static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado:.
        /// </summary>
        internal static string UnexpectedErrorMSG {
            get {
                return ResourceManager.GetString("UnexpectedErrorMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização.
        /// </summary>
        internal static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma nova ataulização está disponível e a aplicação precisa reiniciar antes de prosseguir..
        /// </summary>
        internal static string UpgradeNeededMSG {
            get {
                return ResourceManager.GetString("UpgradeNeededMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome usuário precisa ser único..
        /// </summary>
        internal static string UsernameMustBeUniqueMSG {
            get {
                return ResourceManager.GetString("UsernameMustBeUniqueMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificadas.
        /// </summary>
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilidades.
        /// </summary>
        internal static string Vulnerabilities {
            get {
                return ResourceManager.GetString("Vulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilidade.
        /// </summary>
        internal static string Vulnerability {
            get {
                return ResourceManager.GetString("Vulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo ao GUI Client do Netrisk..
        /// </summary>
        internal static string WelcomeMSG {
            get {
                return ResourceManager.GetString("WelcomeMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não pode apagar o próprio usuário..
        /// </summary>
        internal static string YouCannotDeleteYourselfMSG {
            get {
                return ResourceManager.GetString("YouCannotDeleteYourselfMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não pode desabilitar a si mesmo..
        /// </summary>
        internal static string YouCannotDisableYourselfMSG {
            get {
                return ResourceManager.GetString("YouCannotDisableYourselfMSG", resourceCulture);
            }
        }
    }
}
